# Generated by Django 4.0.2 on 2022-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionny_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='anunt',
            field=models.IntegerField(null=True),
        ),
    ]
