# Generated by Django 4.0.2 on 2022-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ionny_store', '0002_contact_anunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='anunt',
            field=models.TextField(null=True),
        ),
    ]
